"""slas_fetch: resumable, checksummed model-weight fetches from the hub (standard library only).

Used by `scripts/fetch_models.py` on a connected host before the stack starts (ADR-0014)
and by the `model-fetcher` service on a connected quickstart host (ADR-0018). The names
below are the package's public surface; `main` is the command line.
"""

from __future__ import annotations

from slas_fetch.cli import build_parser, iter_sources, main
from slas_fetch.fetch import (
    ALWAYS_REDUNDANT,
    CHUNK,
    DEFAULT_ENDPOINT,
    DEFAULT_HUB_HOSTS,
    PROFILES,
    REDUNDANT_WHEN_SAFETENSORS,
    FetchCancelledError,
    FetchedModel,
    FetchError,
    Hub,
    ModelPlan,
    Opener,
    Progress,
    ProgressCallback,
    RemoteFile,
    Source,
    allowlisted_opener,
    already_here,
    blob_sha1,
    check_disk,
    fetch_planned,
    free_bytes,
    host_allowed,
    host_of,
    human,
    is_complete,
    merge_manifest,
    not_allowed,
    part_of,
    plan_model,
    read_manifest,
    read_sources,
    read_sums,
    select,
    sha256_of,
    strip_comment,
    verify,
    write_atomic,
    write_manifest,
    write_sums,
)

__version__ = "0.0.1"

__all__ = [
    "ALWAYS_REDUNDANT",
    "CHUNK",
    "DEFAULT_ENDPOINT",
    "DEFAULT_HUB_HOSTS",
    "PROFILES",
    "REDUNDANT_WHEN_SAFETENSORS",
    "FetchCancelledError",
    "FetchError",
    "FetchedModel",
    "Hub",
    "ModelPlan",
    "Opener",
    "Progress",
    "ProgressCallback",
    "RemoteFile",
    "Source",
    "allowlisted_opener",
    "already_here",
    "blob_sha1",
    "build_parser",
    "check_disk",
    "fetch_planned",
    "free_bytes",
    "host_allowed",
    "host_of",
    "human",
    "is_complete",
    "iter_sources",
    "main",
    "merge_manifest",
    "not_allowed",
    "part_of",
    "plan_model",
    "read_manifest",
    "read_sources",
    "read_sums",
    "select",
    "sha256_of",
    "strip_comment",
    "verify",
    "write_atomic",
    "write_manifest",
    "write_sums",
]
