"""`skills/schema/skill.schema.json`, generated from the primitive table and §6.1.

The file is what editors, the WebUI and other installations validate against; the same
table drives the in-process import, so the two cannot drift (a test keeps the file in step).
"""

from __future__ import annotations

import json
from typing import Any, Final

from slas_authz import SKILL_REQUIRES
from slas_skills.primitives import MAX_WAIT_SECONDS, PRIMITIVES, REDFISH_ACTIONS
from slas_skills.schema import SEMVER, SLUG

SCHEMA_ID: Final = "https://slas.local/schemas/skill.schema.json"

_ARG_TYPES: Final[dict[str, dict[str, Any]]] = {
    "x": {"type": "integer", "minimum": 0},
    "y": {"type": "integer", "minimum": 0},
    "amount": {"type": ["integer", "string"]},
    "timeout_s": {"type": ["integer", "string"], "minimum": 1},
    "seconds": {"type": ["integer", "number", "string"], "minimum": 0, "maximum": MAX_WAIT_SECONDS},
    "expect_exit": {"type": ["integer", "string"]},
    "capture": {"type": ["boolean", "string"]},
    "command": {"type": "array", "items": {"type": "string"}, "minItems": 1},
    "items": {"type": ["array", "string"], "maxItems": 100},
    "then": {"type": "array", "items": {"$ref": "#/$defs/step"}, "minItems": 1},
    "else": {"type": "array", "items": {"$ref": "#/$defs/step"}, "minItems": 1},
    "action": {"enum": sorted(REDFISH_ACTIONS)},
    "direction": {"enum": ["up", "down", "left", "right"]},
}


def _arg(name: str) -> dict[str, Any]:
    return dict(_ARG_TYPES.get(name, {"type": "string"}))


def _step_variant(name: str) -> dict[str, Any]:
    spec = PRIMITIVES[name]
    args: dict[str, Any] = {
        "type": "object",
        "description": spec.description,
        "properties": {arg: _arg(arg) for arg in sorted(spec.known_args())},
        "required": list(spec.required),
        "additionalProperties": False,
    }
    if spec.one_of:
        args["anyOf"] = [{"required": list(group)} for group in spec.one_of]
    return {
        "type": "object",
        "properties": {
            name: args,
            "id": {"type": "string", "pattern": SLUG},
            "when": {"type": "string"},
        },
        "required": [name],
        "additionalProperties": False,
    }


def build_skill_schema() -> dict[str, Any]:
    return {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": SCHEMA_ID,
        "title": "SW Local Agent Service skill",
        "description": "A skill recipe: whitelisted steps only (CLAUDE.md §6). Generated by "
        "slas_skills.jsonschema.build_skill_schema(); do not edit by hand.",
        "type": "object",
        "properties": {"skill": {"$ref": "#/$defs/skill"}},
        "required": ["skill"],
        "additionalProperties": False,
        "$defs": {
            "skill": {
                "type": "object",
                "properties": {
                    "id": {"type": "string", "pattern": SLUG},
                    "name": {"type": "string", "minLength": 1, "maxLength": 120},
                    "version": {"type": "string", "pattern": SEMVER},
                    "description": {"type": "string"},
                    "agents": {
                        "type": "array",
                        "items": {"enum": ["coding", "validation", "factory"]},
                        "minItems": 1,
                        "uniqueItems": True,
                    },
                    "requires": {
                        "type": "array",
                        "items": {"enum": sorted(c.value for c in SKILL_REQUIRES)},
                        "uniqueItems": True,
                    },
                    "timeout_s": {"type": "integer", "minimum": 1, "maximum": 86400},
                    "inputs": {
                        "type": "object",
                        "additionalProperties": {"$ref": "#/$defs/input"},
                    },
                    "steps": {
                        "type": "array",
                        "items": {"$ref": "#/$defs/step"},
                        "minItems": 1,
                        "maxItems": 200,
                    },
                    "on_failure": {
                        "oneOf": [
                            {"enum": ["stop", "screenshot_and_stop", "continue"]},
                            {
                                "type": "object",
                                "properties": {
                                    "retry": {
                                        "type": "object",
                                        "properties": {
                                            "max": {"type": "integer", "minimum": 1, "maximum": 10},
                                            "delay_s": {
                                                "type": "integer",
                                                "minimum": 0,
                                                "maximum": 600,
                                            },
                                        },
                                        "required": ["max"],
                                        "additionalProperties": False,
                                    }
                                },
                                "required": ["retry"],
                                "additionalProperties": False,
                            },
                        ]
                    },
                    "outputs": {
                        "type": "object",
                        "additionalProperties": {
                            "type": "object",
                            "properties": {"from": {"type": "string", "minLength": 1}},
                            "required": ["from"],
                            "additionalProperties": False,
                        },
                    },
                    "sop_summary": {
                        "type": "object",
                        "properties": {"en": {"type": "string"}, "zh": {"type": "string"}},
                        "required": ["en", "zh"],
                        "additionalProperties": False,
                    },
                },
                "required": ["id", "name", "version", "agents", "steps"],
                "additionalProperties": False,
            },
            "input": {
                "type": "object",
                "properties": {
                    "type": {"enum": ["string", "int", "bool", "path", "target_ref", "secret"]},
                    "required": {"type": "boolean"},
                    "default": {},
                    "description": {"type": "string"},
                },
                "required": ["type"],
                "additionalProperties": False,
            },
            "step": {"oneOf": [_step_variant(name) for name in PRIMITIVES]},
        },
    }


def render_skill_schema() -> str:
    return json.dumps(build_skill_schema(), indent=2, ensure_ascii=False) + "\n"
